M48
; DRILL file {KiCad 8.0.8} date 2025-04-03T15:38:06+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-03T15:38:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X102.955Y-84.69
X102.955Y-90.47
T2
X101.0Y-54.0
X101.0Y-124.0
X166.0Y-54.0
X166.0Y-124.0
M30
